### ISSUE TITLE
参考、*.code-workspaceからpersonal.shを書き換えるDenoプログラム

### ISSUE THREAD

**Issue by taisukef** [2ndPINEW/workspace#1]
https://github.com/taisukef/workspace/blob/master/tmux_layout/update.js
ワークスペースとターミナルの開きたいパスが違う場合に非対応

**Comment by 2ndPINEW** [comment]
だいぶ便利かもです

**Comment by 2ndPINEW** [comment]
相対パスで書かれてることもあるのでこうしてあげた方が良いかもです
const sh4 = sh3.replace(/WORKSPACE_PATH=\([^\)]+\)/, "WORKSPACE_PATH=(\n" + files.map(f => "  " + `${Deno.cwd()}/${f.path}`).join("\n") + "\n)\n");

**Comment by 2ndPINEW** [comment]
追加しました
https://github.com/2ndPINEW/workspace/commit/65ae920675833d4f6a401265cf4d2763a1a0abd7
